### ISSUE TITLE
Publish to grafana plugin repo

### ISSUE THREAD

**Issue by nrukavkov** [VolkovLabs/volkovlabs-env-datasource#15]
Please publish to grafana plugin repo

**Comment by mikhail-vl** [comment]
@nrukavkov Thank you for your interesting in the Environment Data Source. Unfortunately, it was rejected because of the security concerns exposing environment variables, which is the whole purpose of it.

  The latest version signed as Private plugin for http://localhost, which works in the most cases if you are using NGINX in front of Grafana.
  You can build and sign it for the specific domain if required.
  
  Let us know if there is anything else.
