### ISSUE TITLE
Cannot install plugin to k8s instance of grafana

### ISSUE THREAD

**Issue by nrukavkov** [VolkovLabs/volkovlabs-env-datasource#16]
Hello. I could not install volkovlabs-env-datasource, can you please help. While string grafana I'got 

```
logger=plugin.loader t=2022-11-23T07:09:16.316292106Z level=info msg="Plugin registered" pluginID=input
logger=plugin.loader t=2022-11-23T07:09:16.334529842Z level=warn msg="Could not find root URL that matches running application URL" plugin=volkovlabs-env-datasource appUrl=https://grafana.preview30.k8s-cluster02.mydomain.com/ rootUrls=[http://localhost:3000/]
logger=plugin.loader t=2022-11-23T07:09:16.334574642Z level=warn msg="Skipping loading plugin due to problem with signature" pluginID=volkovlabs-env-datasource status=invalid
```

Grafana configuration is changing using env variables:

```
- name: GF_DEFAULT_APP_MODE
  value: development
- name: GF_SERVER_DOMAIN
  value: grafana.preview30.k8s-cluster02.appulate.dev
- name: GF_SERVER_ROOT_URL
  value: https://grafana.preview30.k8s-cluster02.appulate.dev
- name: GF_SERVER_HTTP_PORT
  value: '3000'
- name: GF_SECURITY_ADMIN_PASSWORD
  value: foobar
- name: GF_USERS_ALLOW_SIGN_UP
  value: 'false'
- name: GF_SECURITY_CSRF_TRUSTED_ORIGINS
  value: https://grafana.preview30.k8s-cluster02.appulate.dev
- name: GF_SECURITY_CSRF_ADDITIONAL_HEADERS
  value: X-Forwarded-Host
- name: GF_INSTALL_PLUGINS
  value: "https://github.com/VolkovLabs/volkovlabs-env-datasource/releases/download/v2.2.0/volkovlabs-env-datasource-2.2.0.zip;volkovlabs-env-datasource"
- name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
  value: volkovlabs-env-datasource
```

Can you help to do it right way? =)

**Comment by mikhail-vl** [comment]
@nrukavkov Environment Data Source is a Private plugin signed for`rootUrls=[http://localhost:3000/]`. I will update README to make it clear.

  It's unable to load because your domain is set to `https://grafana.preview30.k8s-cluster02.mydomain.com/ ` according to the error message:

```
appUrl=https://grafana.preview30.k8s-cluster02.mydomain.com/ rootUrls=[http://localhost:3000/]
```

  We recommend using NGINX in front of the Grafana for an extra level of protection, which also allows keeping the default domain as `http://localhost:3000`.
  Other options are:
  - Build the plugin and sign it for your custom domain.
  - Allow Unsigned plugins: https://volkovlabs.io/plugins/grafana-allow-unsigned/ 

  Please let me know if you have any questions.

**Comment by mikhail-vl** [comment]
@nrukavkov To allow loading unsigned plugins to work like in your configuration, you will need to remove the `MANIFEST.txt` file from the archive and host it locally.

**Comment by MkrierPharmanity** [comment]
> @nrukavkov To allow loading unsigned plugins to work like in your configuration, you will need to remove the `MANIFEST.txt` file from the archive and host it locally.

can you add a unsigned version on the release page of github ?  ( ie : volkovlabs-env-datasource-3.1.0.unsigned.zip )

**Comment by mikhail-vl** [comment]
@MkrierPharmanity I will in the upcoming release.
